name: reconvat-gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - torch==1.13.1
      - torchvision==0.14.1
      - tensorboard==2.2.0
      - numpy==1.19.5
      - matplotlib==3.3.4
      - sacred==0.8.1
      - nnAudio==0.2.0
      - mir_eval==0.5
      - pandas==1.1.5
      - SoundFile==0.10.2
      - tqdm
      - mido==1.2.9
      - joblib==1.0.1
      - scikit-learn==0.24.2
      - pydub==0.23.1
      - protobuf==3.20.3